name: "Trigger: on Release"


on:
  release:
    types: [published]


jobs:

  build-wheel:
    uses: ./.github/workflows/build_wheel.yml

  # build-docs:
  #   uses: ./.github/workflows/build_docs.yml

  deploy-release:
    name: Deploy assets to release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs:
      - build-wheel
      # - build-rpms

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get install hub

      - name: Fetch Wheel
        uses: actions/download-artifact@v4
        with:
          name: Wheel
          path: dist

      # - name: Fetch Notes
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: Notes

      # - name: Upload release notes
      #   run: |
      #     gh release edit ${{ github.ref_name }} \
      #       -F release.md
      #   env:
      #     GITHUB_TOKEN: ${{ github.TOKEN }}

      - name: Upload python dist content
        run: |
          gh release upload ${{ github.ref_name }} \
            dist/*.whl
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

  # deploy-docs:
  #   name: Deploy documentation
  #   runs-on: ubuntu-latest

  #   needs:
  #     - build-docs

  #   permissions:
  #     pages: write
  #     id-token: write

  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deploy.outputs.page_url }}

  #   steps:
  #     - name: Deploy site
  #       id: deploy
  #       uses: actions/deploy-pages@v4

  deploy-pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    needs:
      - build-wheel

    environment:
      name: pypi
      url: https://pypi.org/p/kojismokydingo

    permissions:
      id-token: write

    steps:
      - name: Fetch python dist content
        uses: actions/download-artifact@v4
        with:
          name: Wheel
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  # announce:
  #   name: Announce release
  #   runs-on: ubuntu-latest

  #   needs:
  #     - deploy-release
  #     - deploy-docs
  #     - deploy-pypi

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Fetch python dist content
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: Version

  #     - name: Get the package version
  #       run: |
  #         echo "DIST_VERSION=$(cat VERSION)" >> "$GITHUB_ENV"

  #     - name: Get current date
  #       run: |
  #         echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

  #     - name: Post announcement
  #       uses: ./.github/workflows/run_announce.yml
  #       with:
  #         version: ${{ env.DIST_VERSION }}
  #         date: ${{ env.RELEASE_DATE }}
  #         ref: ${{ github.ref_name }}


# The end.
